### ISSUE TITLE
add asMailString()

### ISSUE THREAD

**Issue by RodrigoDornelles** [evanshortiss/env-var#146]
**Is your feature request related to a problem? Please describe.**
is something interesting, there is an email validation when string, I would liken [...]

**Describe the solution you'd like**
do a regex validation over email, someone can refine it in the future and check IDN and DNS

**Additional context**
```JS
const email = env.get('MAIL_USER').asMailString();
```

**Comment by evanshortiss** [comment]
@RodrigoDornelles this is a good suggestion. I've had to do this before, though I was lazy and used `asString()`.

The one issue with this is how strict the implementation is. There are a few good suggestions in this [StackOverflow post](https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression) and [this one too](https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript). 

Personally I would accept a PR that does a simple regex, then mention this in the module docs. Aiming for full RFC compliance is not necessary since it would require using a third party [module like this one](https://www.npmjs.com/package/email-addresses).

Do you want to open a PR?

**Comment by RodrigoDornelles** [comment]
i think so, i'm not very familiar with regex and am typescript's noob, but i'll try anyway... carefully review my PR!

**Comment by bigen1925** [comment]
Hi guys,

Thank you for providing this simple and awesome library, I love this. :D

And I will be also happy if this feature will be implemented, but there seems to be no progress in months, so I opened a PR.

https://github.com/evanshortiss/env-var/pull/158

I'm happy to be reviewed.

**Comment by evanshortiss** [comment]
Released this in version 7.2.0. Thank you all.
