### ISSUE TITLE
Allow asUrlString (and maybe other checks) to be optional

### ISSUE THREAD

**Issue by AxTrusov** [evanshortiss/env-var#167]
**Is your feature request related to a problem? Please describe.**

Imagine that you have a default configuration with optional variables, one of which is for URL e.g.
```text
TEST_STRING=
TEST_URL=
```

And you request them as such:
```ts
const str = env.get('TEST_STRING').asString();
const url = env.get('TEST_URL').asUrlString();
```
In this case, the first line will pass, but the second one will throw an error, because the value will resolve to an empty string, which is not an url string. Logically, this behavior makes sense, but it would be nice to allow the variable to remain empty and skip the whole IsUrl validation, only checking if value is not empty.

**Describe the solution you'd like**
Maybe something like this?
```ts
const url = env.get('TEST_URL').optional().asUrlString();
```

**Describe alternatives you've considered**
The only alternative is to comment out the variable in the .env file, but having it in an uncommented state gives a clear indication that variable is not obsolete (not just some random comment), and that it is optional and can be filled with a value.

**Additional context**
Tested using env-var 6.3.0, have not found any other meaningful alternatives.

**Comment by evanshortiss** [comment]
Overall I see this as a question of how `env-var` should handle `undefined` and `''` (empty  string) values. 

I suppose a string of length zero could be considered equivalent to the variable being unset, but this would be a breaking change that requires a major version bump just to be safe. 

Also, in the case of `asString()` what should happen? In your example `TEST_STRING` is set to an empty string, but if `env-var` was changed to interpret that as unset then it would return `undefined` instead of the empty string. A developer might expect to receive the empty string, and not undefined in that scenario.

Since `required()` already exists, I don't think it makes sense to add the `optional` function. I'll need to think on this one 🤔

**Comment by evanshortiss** [comment]
OK, after running it by others I think my initial reaction was the right one. 

The best option is to comment out `TEST_URL=` (so it's not set to an invalid URL string), or add some logic in your codebase if you want to set it to an empty string. You could implement a function that resembles this:

```js
// Use asString to read an empty string, or get undefined if the variable is not set
const urlStr = env.get('TEST_URL').asString();

if (urlStr && urlStr !== '') {
  // Maybe add a try/catch here depending on your needs
  return env.accessors.asUrlString(urlStr)
} else {
  // Return undefined if TEST_URL is set to "" or is undefined
  return undefined
}
```
