### ISSUE TITLE
feature request: asEnum(['list', 'of', 'valid, 'values'])

### ISSUE THREAD

**Issue by hhravn** [evanshortiss/env-var#21]
... or maybe `env.get('VARIABLE').required().asString().oneOf(['list', 'of', 'valid, 'values'])`

We have a few places where we do a second iteration of validation. Would be nice to have this all taken care of by `env-var` ;)

**Comment by evanshortiss** [comment]
@hhravn this is something I thought of before, but wasn't 100% decided on. The main goal of this module is to ensure variables load with correct typings and I was concerned that this extends the scope too much.

Doing `.asString().oneOf` would be more complex due to the module design right now. I like the idea of `asEnum()` though since it's a reasonably common use case.

Do you plan to make a PR? Should be relatively easy, just add `as-enum.js` in [this directory](https://github.com/evanshortiss/env-var/tree/master/lib/accessors) then load it [here](https://github.com/evanshortiss/env-var/blob/master/lib/variable.js#L63).

**Comment by evanshortiss** [comment]
Thanks @hhravn. Released as version 3.3.0
