### ISSUE TITLE
Ability to override process.env

### ISSUE THREAD

**Issue by shawnmclean** [evanshortiss/env-var#39]
In a case of using Create-React-App, it seems they are doing something funky with their `process` variable. That is, if you access process  via require or import, it will be null. So this lib will never get the env vars set in by this app.

Would you mind adding an extra param for `get(envVar, default, container)` that allows us to pass in our own `process.env` as the 3rd param?

I could do a PR  if you prefer that route.

**Comment by evanshortiss** [comment]
That's interesting. I've only used `create-react-app` a few times so never came across this. Nice find.

If we just removed [this line](https://github.com/evanshortiss/env-var/blob/master/env-var.js#L3) would the problem be fixed? 

Or would a better solution be to change the module behaviour so it works like so:

```
// Pass in the container
const env = require('env-var')(process)
```

This would be a major version bump of course, and would mean we could remove `env.mock`. This is probably better since it's a more flexible approach.

What do you think?

**Comment by evanshortiss** [comment]
@shawnmclean want to PR the removal of the `require` I'll merge and release it as a MINOR release.

**Comment by evanshortiss** [comment]
@shawnmclean #42 should solve your issue. It also changes the `env.mock` function name to something more appropriate so developers know they can use it to create `env` instances that read from whatever object they need, not just `process.env`

**Comment by evanshortiss** [comment]
@shawnmclean I'd still welcome a PR on previous master to release as a patch for 3.x so if you have something I'd marge it into a 3.x branch and make a release 👍

**Comment by evanshortiss** [comment]
Closing this @shawnmclean. Feel free to reopen if you need
